version: '3'
services:
  capturer:
    image: capturer:1.0
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/vfio
    volumes:
      - /dev/hugepages:/dev/hugepages
    environment:
      DPDK_HUGEPAGES: 1G
    command: ["-i", "ens77", "-pci", "0000:02:05.0", "-kafka", "192.168.3.93:9092"]
